# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - datatalker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://datatalker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6deb2ee3abf54032b7337bc52208e6e8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0550e046fbfb49c3862d89ade6d8e712 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: datatalker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6deb2ee3abf54032b7337bc52208e6e8 }}/datatalker/deep_talker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'datatalker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_890a5ae6d25a4abf8406cae28416cd63 }}
        images: 'datatalker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6deb2ee3abf54032b7337bc52208e6e8 }}/datatalker/deep_talker:${{ github.sha }}'